language: python
python:
  - "3.8"

services:
  - docker
# - postgres

install:
    - pip install -r requirements.txt

before_script: pip install docker-compose

script:
  - docker-compose up
  - docker-compose run --rm consultant sh -c "python manage.py test"
deploy:
    provider: script
    skip_cleanup: true
    on:
        branch: Deployment